version: '3.8'

services:
  audiobooks-manager:
    build: .
    container_name: audiobooks-manager
    restart: unless-stopped
    ports:
      - "56176:53509"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres  # Anpassen an Ihre DB-Konfiguration
    networks:
      - existing_network  # Name Ihres bestehenden Docker-Netzwerks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:53509/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  existing_network:
    external: true